# Change these first
owner: taichi-dev # Your GitHub organization or username, where this repository lives
repo: taitopia-status-page # The name of this repository
user-agent: taitopia-status-probe

sites:
  - name: Burrito
    url: https://dianshiapp.com
    method: GET
    assignees:
      - imcom
      - JinkunSun
      - TobeBetterV
      - k-ye
      - knight42
      - maajor
      - m1911star
      - rexwangcc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dianshiapp.com
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.dianshiapp.com/burrito/landing/kv/kv_0923.png
  name: Status page of Taitopia services
  introTitle: "This is the status page of some of the **Taitopia** public-facing services"
  introMessage: Welcome to the status page of Taitopia, we are sorry if you run into incidents due to downtime of our services!
  navbar:
    - title: Status
      href: /
    - title: 点石 3D
      href: http://dianshiapp.com
    - title: 点石 3D 社群
      href: https://support.qq.com/products/434464

i18n:
  footer: Status Page of 点石 3D

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  # every 6 hours
  uptime: "0 */6 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
